import {spawn} from 'node:child_process';
import {mkdtemp, readFile, writeFile, mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const url = 'http://127.0.0.1:8766';
const profile = await mkdtemp(join(tmpdir(), 'athena-studio-smoke-'));
const chrome = spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', ['--headless=new','--disable-gpu','--in-process-gpu','--no-sandbox','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'], {windowsHide:true,stdio:['ignore','ignore','pipe']});
let socket, sequence = 0;
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const pending = new Map(), errors = [];
try {
  let port;
  for (let i=0;i<100;i++) { try {port=(await readFile(join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch{await sleep(100);} }
  assert.ok(port, 'Chrome started');
  const pages = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  socket = new WebSocket(pages[0].webSocketDebuggerUrl);
  await new Promise(resolve => socket.addEventListener('open',resolve,{once:true}));
  socket.addEventListener('message',event=>{const msg=JSON.parse(event.data);if(msg.id){const task=pending.get(msg.id);pending.delete(msg.id);msg.error?task.reject(msg.error):task.resolve(msg.result);}else if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails.text);});
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
  const until=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await sleep(100);}throw new Error(`Timed out: ${expression}`);};
  await send('Runtime.enable'); await send('Page.enable');
  const jobs=await(await fetch(url+'/api/jobs')).json();
  await send('Page.navigate',{url:`${url}/books/${jobs[0].id}/studio`});
  await until('document.getElementById("title")?.textContent === "The Door" && !document.getElementById("generate-book").disabled');
  assert.equal(await evaluate('document.getElementById("chapters").children.length'),2);
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
  await evaluate('document.getElementById("chapters").children[1].click()');
  assert.equal(await evaluate('document.getElementById("prose").textContent'),'At dawn she returned.');
  await evaluate('document.getElementById("generate-book").click()');
  await until('!document.getElementById("master-download").hidden');
  await evaluate('document.getElementById("tab-masters").click()');
  assert.equal(await evaluate('document.querySelectorAll(".master-card a[download]").length'),2);
  await evaluate('document.querySelector(".master-card button").click()');
  await until('document.getElementById("audio").readyState >= 1');
  assert.equal(await evaluate('document.getElementById("audio").duration'),3);
  await evaluate('document.getElementById("audio").pause(); document.getElementById("playback-speed").value="1.5"; document.getElementById("playback-speed").dispatchEvent(new Event("change"))');
  assert.equal(await evaluate('document.getElementById("audio").playbackRate'),1.5);
  await send('Page.reload');
  await until('document.querySelectorAll(".master-card a[download]").length === 2');
  await evaluate('document.getElementById("tab-voices").click()');
  await evaluate('document.getElementById("speech-voice").value="af_bella"; document.getElementById("voice-form").requestSubmit()');
  await until('document.getElementById("message").textContent.includes("settings saved")');
  await evaluate('document.getElementById("tab-manuscript").click()');
  await mkdir('artifacts',{recursive:true});
  await writeFile('artifacts/athena-audiobook-desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await sleep(100);
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'),true,'Studio fits mobile');
  await writeFile('artifacts/athena-audiobook-mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
  assert.deepEqual(errors,[]);
  console.log('Studio browser passed: chapters, full narration through a local HTTP speech fixture, playback, speed, downloads, reload persistence, voice settings, desktop/mobile layout.');
}finally{socket?.close();chrome.kill();}
