import os
import json
import re
from job_runner import atomic_json


def _extract_json_from_response(content: str) -> str:
    """Extract a JSON block from a model response that may contain preamble prose
    or markdown fences around the JSON.  Returns the bare JSON string."""
    content = content.strip()

    # 1. Prefer an explicit ```json ... ``` fence block anywhere in the response
    fenced = re.search(r'```(?:json)?\s*([\s\S]*?)```', content)
    if fenced:
        return fenced.group(1).strip()

    # 2. Try to find the outermost JSON object or array using brace/bracket matching
    for start_char, end_char in (('{', '}'), ('[', ']')):
        idx = content.find(start_char)
        if idx != -1:
            depth = 0
            in_string = False
            escape_next = False
            for i, ch in enumerate(content[idx:], start=idx):
                if escape_next:
                    escape_next = False
                    continue
                if ch == '\\' and in_string:
                    escape_next = True
                    continue
                if ch == '"':
                    in_string = not in_string
                    continue
                if in_string:
                    continue
                if ch == start_char:
                    depth += 1
                elif ch == end_char:
                    depth -= 1
                    if depth == 0:
                        return content[idx:i + 1]

    # 3. Fallback: return as-is and let json.loads surface the real error
    return content

class MemoryManager:
    def __init__(self, base_dir: str):
        self.base_dir = base_dir
        self.memory_dir = os.path.join(base_dir, "08_Memory")
        self.schema_dir = os.path.join(self.memory_dir, "schemas")
        self.chapters_dir = os.path.join(self.memory_dir, "chapters")
        os.makedirs(self.chapters_dir, exist_ok=True)

    def load_schema(self, schema_name: str) -> str:
        """Loads a JSON schema as a string to be passed into the prompt."""
        filepath = os.path.join(self.schema_dir, schema_name)
        if not os.path.exists(filepath):
            return ""
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()

    def load_artifact(self, artifact_name: str) -> str:
        """Loads a saved artifact (like outline.json or story_bible.json)."""
        filepath = os.path.join(self.memory_dir, artifact_name)
        if not os.path.exists(filepath):
            return "{}"
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
           
    def save_artifact(self, artifact_name: str, content: str):
        """Saves a JSON artifact generated by an LLM."""
        # Extract the JSON block from the response (handles preamble prose + fences)
        content = _extract_json_from_response(content)
           
        filepath = os.path.join(self.memory_dir, artifact_name)
       
        # Validate it's actually JSON before saving
        try:
            json_data = json.loads(content)
            if re.fullmatch(r'chapter_\d+(?:_varied|_dialogue_revised)?\.json', artifact_name):
                if not isinstance(json_data, dict) or not isinstance(json_data.get('prose_content'), str) or not json_data['prose_content'].strip():
                    raise ValueError(f'{artifact_name} must contain nonempty prose_content.')
            atomic_json(filepath, json_data)
            print(f"Saved artifact to {filepath}")
        except json.JSONDecodeError as e:
            print(f"Error: Model did not output valid JSON for {artifact_name}: {e}")
            # Save raw anyway for debugging
            with open(filepath + ".raw", 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Saved raw output to {filepath}.raw")
            raise ValueError(f'Invalid JSON for {artifact_name}; raw response saved.') from e

    def save_text_artifact(self, artifact_name: str, content: str):
        """Saves a non-JSON artifact (markdown/plain text) as-is, no JSON validation.
        Use for things like corrections logs, blurbs, front/back matter, manuscript.md
        that aren't structured JSON per the service's Interface Contract."""
        content = content.strip()
        filepath = os.path.join(self.memory_dir, artifact_name)
        temporary = filepath + '.tmp'
        with open(temporary, 'w', encoding='utf-8') as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(temporary, filepath)
        print(f"Saved text artifact to {filepath}")

    def get_chapter_tail(self, chapter_number: int, word_count: int = 500) -> str:
        """Get the final N words of a chapter's prose."""
        if chapter_number < 1:
            return ""
        
        chapter_file = os.path.join(self.memory_dir, f"chapter_{chapter_number:02d}.json")
        if not os.path.exists(chapter_file):
            return ""
        
        try:
            with open(chapter_file, 'r', encoding='utf-8') as f:
                chapter_data = json.load(f)
            
            # Extract prose content - try different possible fields
            prose = chapter_data.get("prose_content", "") or chapter_data.get("content", "") or str(chapter_data)
            
            words = prose.split()
            if len(words) <= word_count:
                return prose
            
            return " ".join(words[-word_count:])
        except:
            return ""

    def save_chapter_summary(self, chapter_number: int, summary_data: dict):
        """Save chapter summary to chapters/ directory."""
        filepath = os.path.join(self.chapters_dir, f"chapter_{chapter_number:02d}_summary.json")
        atomic_json(filepath, summary_data)
        print(f"Saved chapter summary to {filepath}")

    def load_chapter_summary(self, chapter_number: int) -> dict:
        """Load a single chapter summary."""
        filepath = os.path.join(self.chapters_dir, f"chapter_{chapter_number:02d}_summary.json")
        if not os.path.exists(filepath):
            return {}
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)

    def load_chapter_summaries_up_to(self, chapter_number: int) -> list:
        """Load all chapter summaries up to and including the given chapter."""
        summaries = []
        for i in range(1, chapter_number + 1):
            summary = self.load_chapter_summary(i)
            if summary:
                summaries.append(summary)
        return summaries

    def load_chapters_up_to(self, chapter_number: int) -> list:
        """Load full chapter data up to the given chapter."""
        chapters = []
        for i in range(1, chapter_number + 1):
            chapter_file = os.path.join(self.memory_dir, f"chapter_{i:02d}.json")
            if os.path.exists(chapter_file):
                with open(chapter_file, 'r', encoding='utf-8') as f:
                    chapters.append(json.load(f))
        return chapters

    def get_context_fragment(self, chapter_number: int) -> dict:
        """Get Story Bible context fragment relevant to a specific chapter.
        Returns only character profiles, location details, and world rules 
        relevant to the specified chapter - not the entire bible.
        """
        story_bible = self.load_artifact("story_bible.json")
        try:
            data = json.loads(story_bible)
        except:
            return {}
        
        # Extract chapter-specific context
        # This would ideally use chapter roadmap to know which characters/locations appear
        # For now, return the full bible but this is the extension point
        return {
            "character_profiles": data.get("character_profiles", {}),
            "location_registry": data.get("location_registry", {}),
            "world_rules": data.get("world_rules", {}),
            "timeline": data.get("timeline", []),
            "mysteries": data.get("mysteries", []),
            "relationships": data.get("relationships", {}),
            "objects": data.get("objects", {}),
            "information_log": data.get("information_log", {})
        }
